services:
  web:
    extends:
      service: web
      file: web/compose.yml
    environment:
      - VITE_BACKEND_URL=http://api:8080/
      - VITE_TARGET_ENV=development
    env_file:
      - .env.web
  api:
    extends:
      service: api
      file: backend/compose.yml
    environment:
      - DATABASE_DSN=host=database user=postgres password=postgres dbname=app port=5432
      - LOGGER_MOD=plain
    env_file:
      - .env.backend
  database:
    extends:
      service: database
      file: backend/compose.yml
  database.migration:
    extends:
      service: database.migration
      file: backend/compose.yml