packages:
  github.com/mistribe/subtracker/internal/domain/auth:
    config:
      dir: ./internal/domain/auth/mocks
    interfaces:
      Service:
  github.com/mistribe/subtracker/internal/domain/currency:
    config:
      dir: ./internal/domain/currency/mocks
    interfaces:
      Repository:
      Service:
  github.com/mistribe/subtracker/internal/domain/family:
    config:
      dir: ./internal/domain/family/mocks
    interfaces:
      Repository:
  github.com/mistribe/subtracker/internal/domain/label:
    config:
      dir: ./internal/domain/label/mocks
    interfaces:
      Repository:
  github.com/mistribe/subtracker/internal/domain/provider:
    config:
      dir: ./internal/domain/provider/mocks
    interfaces:
      Repository:
  github.com/mistribe/subtracker/internal/domain/subscription:
    config:
      dir: ./internal/domain/subscription/mocks
    interfaces:
      Repository:
  github.com/mistribe/subtracker/internal/domain/user:
    config:
      dir: ./internal/domain/user/mocks
    interfaces:
      Repository:
      Service: