all: false
dir: "{{.InterfaceDir}}"
filename: "{{.InterfaceName | snakecase}}_mock.go"
force-file-write: true
formatter: goimports
log-level: info
structname: "{{.Mock}}{{.InterfaceName}}"
pkgname: "{{.SrcPackageName}}"
recursive: false
template: testify
packages:
  github.com/mistribe/subtracker/internal/adapters/http/export:
    config:
      dir: ./internal/adapters/http/export
    interfaces:
      LabelResolver:
      ProviderResolver:
  github.com/mistribe/subtracker/internal/domain/account:
    config:
      dir: ./internal/domain/account
    interfaces:
      ConnectedAccount:
  github.com/mistribe/subtracker/internal/ports:
    config:
      dir: ./internal/ports
    interfaces:
      IdentityProvider:
      Exchange:
      Authentication:
      EntitlementResolver:
      AccountService:
      Cache:
      CacheLeveled:
      CurrencyRepository:
      FamilyRepository:
      LabelRepository:
      ProviderRepository:
      SubscriptionRepository:
      Authorization:
      PermissionRequest:
      AccountRepository:
      QuotaService:
      UsageRepository:
