all: false
dir: '{{.InterfaceDir}}'
filename: "{{.InterfaceName | snakecase}}_mock.go"
force-file-write: true
formatter: goimports
log-level: info
structname: '{{.Mock}}{{.InterfaceName}}'
pkgname: '{{.SrcPackageName}}'
recursive: false
template: testify
packages:
  github.com/mistribe/subtracker/internal/ports:
    config:
      dir: ./internal/ports
    interfaces:
      IdentityProvider:
      Exchange:
      AuthService:
      UserService:
      LocalCache:
      CurrencyRepository:
      FamilyRepository:
      LabelRepository:
      ProviderRepository:
      SubscriptionRepository:
      UserRepository:
