all: false
dir: '{{.InterfaceDir}}'
filename: "{{.InterfaceName | snakecase}}_mock.go"
force-file-write: true
formatter: goimports
log-level: info
structname: '{{.Mock}}{{.InterfaceName}}'
pkgname: '{{.SrcPackageName}}'
recursive: false
template: testify
packages:
  github.com/mistribe/subtracker/internal/domain/auth:
    config:
      dir: ./internal/domain/auth
    interfaces:
      Service:
  github.com/mistribe/subtracker/internal/domain/currency:
    config:
      dir: ./internal/domain/currency
    interfaces:
      Repository:
      Service:
  github.com/mistribe/subtracker/internal/domain/family:
    config:
      dir: ./internal/domain/family
    interfaces:
      Repository:
  github.com/mistribe/subtracker/internal/domain/label:
    config:
      dir: ./internal/domain/label
    interfaces:
      Repository:
  github.com/mistribe/subtracker/internal/domain/provider:
    config:
      dir: ./internal/domain/provider
    interfaces:
      Repository:
  github.com/mistribe/subtracker/internal/domain/subscription:
    config:
      dir: ./internal/domain/subscription
    interfaces:
      Repository:
  github.com/mistribe/subtracker/internal/domain/user:
    config:
      dir: ./internal/domain/user
    interfaces:
      Repository:
      Service:
  github.com/mistribe/subtracker/internal/infrastructure/cache:
    config:
      dir: ./internal/infrastructure/cache
    interfaces:
      Local:
  github.com/mistribe/subtracker/internal/infrastructure/exchange:
    config:
      dir: ./internal/infrastructure/exchange
    interfaces:
      Client: