// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"

	"github.com/mistribe/subtracker/internal/domain/user"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthorization creates a new instance of MockAuthorization. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthorization(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthorization {
	mock := &MockAuthorization{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthorization is an autogenerated mock type for the Authorization type
type MockAuthorization struct {
	mock.Mock
}

type MockAuthorization_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthorization) EXPECT() *MockAuthorization_Expecter {
	return &MockAuthorization_Expecter{mock: &_m.Mock}
}

// Can provides a mock function for the type MockAuthorization
func (_mock *MockAuthorization) Can(ctx context.Context, permission user.Permission) PermissionRequest {
	ret := _mock.Called(ctx, permission)

	if len(ret) == 0 {
		panic("no return value specified for Can")
	}

	var r0 PermissionRequest
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.Permission) PermissionRequest); ok {
		r0 = returnFunc(ctx, permission)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(PermissionRequest)
		}
	}
	return r0
}

// MockAuthorization_Can_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Can'
type MockAuthorization_Can_Call struct {
	*mock.Call
}

// Can is a helper method to define mock.On call
//   - ctx context.Context
//   - permission user.Permission
func (_e *MockAuthorization_Expecter) Can(ctx interface{}, permission interface{}) *MockAuthorization_Can_Call {
	return &MockAuthorization_Can_Call{Call: _e.mock.On("Can", ctx, permission)}
}

func (_c *MockAuthorization_Can_Call) Run(run func(ctx context.Context, permission user.Permission)) *MockAuthorization_Can_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.Permission
		if args[1] != nil {
			arg1 = args[1].(user.Permission)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthorization_Can_Call) Return(permissionRequest PermissionRequest) *MockAuthorization_Can_Call {
	_c.Call.Return(permissionRequest)
	return _c
}

func (_c *MockAuthorization_Can_Call) RunAndReturn(run func(ctx context.Context, permission user.Permission) PermissionRequest) *MockAuthorization_Can_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureWithinLimit provides a mock function for the type MockAuthorization
func (_mock *MockAuthorization) EnsureWithinLimit(ctx context.Context, feature user.Feature, delta int) error {
	ret := _mock.Called(ctx, feature, delta)

	if len(ret) == 0 {
		panic("no return value specified for EnsureWithinLimit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.Feature, int) error); ok {
		r0 = returnFunc(ctx, feature, delta)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthorization_EnsureWithinLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureWithinLimit'
type MockAuthorization_EnsureWithinLimit_Call struct {
	*mock.Call
}

// EnsureWithinLimit is a helper method to define mock.On call
//   - ctx context.Context
//   - feature user.Feature
//   - delta int
func (_e *MockAuthorization_Expecter) EnsureWithinLimit(ctx interface{}, feature interface{}, delta interface{}) *MockAuthorization_EnsureWithinLimit_Call {
	return &MockAuthorization_EnsureWithinLimit_Call{Call: _e.mock.On("EnsureWithinLimit", ctx, feature, delta)}
}

func (_c *MockAuthorization_EnsureWithinLimit_Call) Run(run func(ctx context.Context, feature user.Feature, delta int)) *MockAuthorization_EnsureWithinLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.Feature
		if args[1] != nil {
			arg1 = args[1].(user.Feature)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthorization_EnsureWithinLimit_Call) Return(err error) *MockAuthorization_EnsureWithinLimit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthorization_EnsureWithinLimit_Call) RunAndReturn(run func(ctx context.Context, feature user.Feature, delta int) error) *MockAuthorization_EnsureWithinLimit_Call {
	_c.Call.Return(run)
	return _c
}
