/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {HttpErrorResponse}
 */
// @ts-ignore
export function createHttpErrorResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoHttpErrorResponse;
}
/**
 * The deserialization information for the current model
 * @param HttpErrorResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoHttpErrorResponse(httpErrorResponse: Partial<HttpErrorResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { httpErrorResponse.messageEscaped = n.getStringValue(); },
    }
}
export interface HttpErrorResponse extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
/**
 * Serializes information the current object
 * @param HttpErrorResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeHttpErrorResponse(writer: SerializationWriter, httpErrorResponse: Partial<HttpErrorResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!httpErrorResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("message", httpErrorResponse.messageEscaped);
    writer.writeAdditionalData(httpErrorResponse.additionalData);
}
/* tslint:enable */
/* eslint-enable */
