// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cache

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockLocal creates a new instance of MockLocal. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLocal(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLocal {
	mock := &MockLocal{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLocal is an autogenerated mock type for the Local type
type MockLocal struct {
	mock.Mock
}

type MockLocal_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLocal) EXPECT() *MockLocal_Expecter {
	return &MockLocal_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockLocal
func (_mock *MockLocal) Get(key string) interface{} {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 interface{}
	if returnFunc, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}
	return r0
}

// MockLocal_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockLocal_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *MockLocal_Expecter) Get(key interface{}) *MockLocal_Get_Call {
	return &MockLocal_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockLocal_Get_Call) Run(run func(key string)) *MockLocal_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLocal_Get_Call) Return(ifaceVal interface{}) *MockLocal_Get_Call {
	_c.Call.Return(ifaceVal)
	return _c
}

func (_c *MockLocal_Get_Call) RunAndReturn(run func(key string) interface{}) *MockLocal_Get_Call {
	_c.Call.Return(run)
	return _c
}

// PurgeExpired provides a mock function for the type MockLocal
func (_mock *MockLocal) PurgeExpired() {
	_mock.Called()
	return
}

// MockLocal_PurgeExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeExpired'
type MockLocal_PurgeExpired_Call struct {
	*mock.Call
}

// PurgeExpired is a helper method to define mock.On call
func (_e *MockLocal_Expecter) PurgeExpired() *MockLocal_PurgeExpired_Call {
	return &MockLocal_PurgeExpired_Call{Call: _e.mock.On("PurgeExpired")}
}

func (_c *MockLocal_PurgeExpired_Call) Run(run func()) *MockLocal_PurgeExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLocal_PurgeExpired_Call) Return() *MockLocal_PurgeExpired_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLocal_PurgeExpired_Call) RunAndReturn(run func()) *MockLocal_PurgeExpired_Call {
	_c.Run(run)
	return _c
}

// Set provides a mock function for the type MockLocal
func (_mock *MockLocal) Set(key string, value interface{}, options ...func(*LocalOptions)) {
	if len(options) > 0 {
		_mock.Called(key, value, options)
	} else {
		_mock.Called(key, value)
	}

	return
}

// MockLocal_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockLocal_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key string
//   - value interface{}
//   - options ...func(*LocalOptions)
func (_e *MockLocal_Expecter) Set(key interface{}, value interface{}, options ...interface{}) *MockLocal_Set_Call {
	return &MockLocal_Set_Call{Call: _e.mock.On("Set",
		append([]interface{}{key, value}, options...)...)}
}

func (_c *MockLocal_Set_Call) Run(run func(key string, value interface{}, options ...func(*LocalOptions))) *MockLocal_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 []func(*LocalOptions)
		var variadicArgs []func(*LocalOptions)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*LocalOptions))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockLocal_Set_Call) Return() *MockLocal_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLocal_Set_Call) RunAndReturn(run func(key string, value interface{}, options ...func(*LocalOptions))) *MockLocal_Set_Call {
	_c.Run(run)
	return _c
}
