/**
 * SubTracker API
 * This api provide HTTPRest endpoints for the application SubTracker.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@mistribe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* @Description Number of free trial days remaining (null if no trial or trial expired)
*/
export class SubscriptionSubscriptionFreeTrialModel {
    'endDate'?: Date;
    'startDate'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "endDate",
            "baseName": "end_date",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "startDate",
            "baseName": "start_date",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionSubscriptionFreeTrialModel.attributeTypeMap;
    }

    public constructor() {
    }
}
