// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package export

import (
	"context"

	"github.com/mistribe/subtracker/internal/domain/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProviderResolver creates a new instance of MockProviderResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProviderResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProviderResolver {
	mock := &MockProviderResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProviderResolver is an autogenerated mock type for the ProviderResolver type
type MockProviderResolver struct {
	mock.Mock
}

type MockProviderResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProviderResolver) EXPECT() *MockProviderResolver_Expecter {
	return &MockProviderResolver_Expecter{mock: &_m.Mock}
}

// ResolveProviderKeys provides a mock function for the type MockProviderResolver
func (_mock *MockProviderResolver) ResolveProviderKeys(ctx context.Context, providerIds []types.ProviderID) (map[types.ProviderID]string, error) {
	ret := _mock.Called(ctx, providerIds)

	if len(ret) == 0 {
		panic("no return value specified for ResolveProviderKeys")
	}

	var r0 map[types.ProviderID]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []types.ProviderID) (map[types.ProviderID]string, error)); ok {
		return returnFunc(ctx, providerIds)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []types.ProviderID) map[types.ProviderID]string); ok {
		r0 = returnFunc(ctx, providerIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[types.ProviderID]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []types.ProviderID) error); ok {
		r1 = returnFunc(ctx, providerIds)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProviderResolver_ResolveProviderKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveProviderKeys'
type MockProviderResolver_ResolveProviderKeys_Call struct {
	*mock.Call
}

// ResolveProviderKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - providerIds []types.ProviderID
func (_e *MockProviderResolver_Expecter) ResolveProviderKeys(ctx interface{}, providerIds interface{}) *MockProviderResolver_ResolveProviderKeys_Call {
	return &MockProviderResolver_ResolveProviderKeys_Call{Call: _e.mock.On("ResolveProviderKeys", ctx, providerIds)}
}

func (_c *MockProviderResolver_ResolveProviderKeys_Call) Run(run func(ctx context.Context, providerIds []types.ProviderID)) *MockProviderResolver_ResolveProviderKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []types.ProviderID
		if args[1] != nil {
			arg1 = args[1].([]types.ProviderID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProviderResolver_ResolveProviderKeys_Call) Return(providerIDToString map[types.ProviderID]string, err error) *MockProviderResolver_ResolveProviderKeys_Call {
	_c.Call.Return(providerIDToString, err)
	return _c
}

func (_c *MockProviderResolver_ResolveProviderKeys_Call) RunAndReturn(run func(ctx context.Context, providerIds []types.ProviderID) (map[types.ProviderID]string, error)) *MockProviderResolver_ResolveProviderKeys_Call {
	_c.Call.Return(run)
	return _c
}
