/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHttpErrorFromDiscriminatorValue, createUserPreferredCurrencyModelFromDiscriminatorValue, serializeUpdatePreferredCurrencyModel, type HttpError, type UpdatePreferredCurrencyModel, type UserPreferredCurrencyModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /users/preferred/currency
 */
export interface CurrencyRequestBuilder extends BaseRequestBuilder<CurrencyRequestBuilder> {
    /**
     * Returns the preferred currency for the authenticated user
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UserPreferredCurrencyModel>}
     * @throws {HttpError} error when the service returns a 401 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<UserPreferredCurrencyModel | undefined>;
    /**
     * Updates the preferred currency for the authenticated user
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {HttpError} error when the service returns a 400 status code
     * @throws {HttpError} error when the service returns a 401 status code
     */
     put(body: UpdatePreferredCurrencyModel, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Returns the preferred currency for the authenticated user
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Updates the preferred currency for the authenticated user
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: UpdatePreferredCurrencyModel, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const CurrencyRequestBuilderUriTemplate = "{+baseurl}/users/preferred/currency";
/**
 * Metadata for all the requests in the request builder.
 */
export const CurrencyRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: CurrencyRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createHttpErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUserPreferredCurrencyModelFromDiscriminatorValue,
    },
    put: {
        uriTemplate: CurrencyRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createHttpErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createHttpErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeUpdatePreferredCurrencyModel,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
