// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth.sql

package sql

import (
	"context"

	"github.com/google/uuid"
)

const getUserFamilyIds = `-- name: GetUserFamilyIds :many
SELECT fm.family_id FROM family_members fm
where fm.user_id = $1
`

func (q *Queries) GetUserFamilyIds(ctx context.Context, userID *string) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getUserFamilyIds, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var family_id uuid.UUID
		if err := rows.Scan(&family_id); err != nil {
			return nil, err
		}
		items = append(items, family_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
