// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sql

import (
	"time"

	"github.com/google/uuid"
)

type Family struct {
	ID        uuid.UUID
	Name      string
	OwnerID   string
	CreatedAt time.Time
	UpdatedAt time.Time
	Etag      string
}

type FamilyMember struct {
	ID        uuid.UUID
	Name      string
	FamilyID  uuid.UUID
	UserID    *string
	Type      string
	CreatedAt time.Time
	UpdatedAt time.Time
	Etag      string
}

type Label struct {
	ID            uuid.UUID
	OwnerType     string
	OwnerFamilyID *uuid.UUID
	OwnerUserID   *string
	Name          string
	Key           *string
	Color         string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Etag          string
}

type Provider struct {
	ID             uuid.UUID
	OwnerType      string
	OwnerFamilyID  *uuid.UUID
	OwnerUserID    *string
	Name           string
	Key            *string
	Description    *string
	IconUrl        *string
	Url            *string
	PricingPageUrl *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Etag           string
}

type ProviderLabel struct {
	LabelID    uuid.UUID
	ProviderID uuid.UUID
}

type ProviderPlan struct {
	ID          uuid.UUID
	Name        string
	Description *string
	ProviderID  uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Etag        string
}

type ProviderPrice struct {
	ID        uuid.UUID
	StartDate time.Time
	EndDate   *time.Time
	Currency  string
	Amount    float64
	PlanID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Etag      string
}

type Subscription struct {
	ID                  uuid.UUID
	OwnerType           string
	OwnerFamilyID       *uuid.UUID
	OwnerUserID         *string
	FriendlyName        *string
	FreeTrialStartDate  *time.Time
	FreeTrialEndDate    *time.Time
	ProviderID          uuid.UUID
	PlanID              *uuid.UUID
	PriceID             *uuid.UUID
	FamilyID            *uuid.UUID
	PayerType           *string
	PayerMemberID       *uuid.UUID
	StartDate           time.Time
	EndDate             *time.Time
	Recurrency          string
	CustomRecurrency    *int32
	CustomPriceCurrency *string
	CustomPriceAmount   *float64
	CreatedAt           time.Time
	UpdatedAt           time.Time
	Etag                string
}

type SubscriptionServiceUser struct {
	FamilyMemberID uuid.UUID
	SubscriptionID uuid.UUID
}
