// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package family

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockRepository
func (_mock *MockRepository) Delete(ctx context.Context, entityId uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, entityId)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, entityId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, entityId)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, entityId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - entityId uuid.UUID
func (_e *MockRepository_Expecter) Delete(ctx interface{}, entityId interface{}) *MockRepository_Delete_Call {
	return &MockRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, entityId)}
}

func (_c *MockRepository_Delete_Call) Run(run func(ctx context.Context, entityId uuid.UUID)) *MockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Delete_Call) Return(b bool, err error) *MockRepository_Delete_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, entityId uuid.UUID) (bool, error)) *MockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockRepository
func (_mock *MockRepository) Exists(ctx context.Context, ids ...uuid.UUID) (bool, error) {
	var tmpRet mock.Arguments
	if len(ids) > 0 {
		tmpRet = _mock.Called(ctx, ids)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, ids...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, ids...)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...uuid.UUID) error); ok {
		r1 = returnFunc(ctx, ids...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockRepository_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - ids ...uuid.UUID
func (_e *MockRepository_Expecter) Exists(ctx interface{}, ids ...interface{}) *MockRepository_Exists_Call {
	return &MockRepository_Exists_Call{Call: _e.mock.On("Exists",
		append([]interface{}{ctx}, ids...)...)}
}

func (_c *MockRepository_Exists_Call) Run(run func(ctx context.Context, ids ...uuid.UUID)) *MockRepository_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		var variadicArgs []uuid.UUID
		if len(args) > 1 {
			variadicArgs = args[1].([]uuid.UUID)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockRepository_Exists_Call) Return(b bool, err error) *MockRepository_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRepository_Exists_Call) RunAndReturn(run func(ctx context.Context, ids ...uuid.UUID) (bool, error)) *MockRepository_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// GetById provides a mock function for the type MockRepository
func (_mock *MockRepository) GetById(ctx context.Context, entityId uuid.UUID) (Family, error) {
	ret := _mock.Called(ctx, entityId)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 Family
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (Family, error)); ok {
		return returnFunc(ctx, entityId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) Family); ok {
		r0 = returnFunc(ctx, entityId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Family)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, entityId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type MockRepository_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - ctx context.Context
//   - entityId uuid.UUID
func (_e *MockRepository_Expecter) GetById(ctx interface{}, entityId interface{}) *MockRepository_GetById_Call {
	return &MockRepository_GetById_Call{Call: _e.mock.On("GetById", ctx, entityId)}
}

func (_c *MockRepository_GetById_Call) Run(run func(ctx context.Context, entityId uuid.UUID)) *MockRepository_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetById_Call) Return(family Family, err error) *MockRepository_GetById_Call {
	_c.Call.Return(family, err)
	return _c
}

func (_c *MockRepository_GetById_Call) RunAndReturn(run func(ctx context.Context, entityId uuid.UUID) (Family, error)) *MockRepository_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserFamily provides a mock function for the type MockRepository
func (_mock *MockRepository) GetUserFamily(ctx context.Context, userId string) (Family, error) {
	ret := _mock.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetUserFamily")
	}

	var r0 Family
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (Family, error)); ok {
		return returnFunc(ctx, userId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) Family); ok {
		r0 = returnFunc(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Family)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetUserFamily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserFamily'
type MockRepository_GetUserFamily_Call struct {
	*mock.Call
}

// GetUserFamily is a helper method to define mock.On call
//   - ctx context.Context
//   - userId string
func (_e *MockRepository_Expecter) GetUserFamily(ctx interface{}, userId interface{}) *MockRepository_GetUserFamily_Call {
	return &MockRepository_GetUserFamily_Call{Call: _e.mock.On("GetUserFamily", ctx, userId)}
}

func (_c *MockRepository_GetUserFamily_Call) Run(run func(ctx context.Context, userId string)) *MockRepository_GetUserFamily_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetUserFamily_Call) Return(family Family, err error) *MockRepository_GetUserFamily_Call {
	_c.Call.Return(family, err)
	return _c
}

func (_c *MockRepository_GetUserFamily_Call) RunAndReturn(run func(ctx context.Context, userId string) (Family, error)) *MockRepository_GetUserFamily_Call {
	_c.Call.Return(run)
	return _c
}

// IsUserMemberOfFamily provides a mock function for the type MockRepository
func (_mock *MockRepository) IsUserMemberOfFamily(ctx context.Context, familyId uuid.UUID, userId string) (bool, error) {
	ret := _mock.Called(ctx, familyId, userId)

	if len(ret) == 0 {
		panic("no return value specified for IsUserMemberOfFamily")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (bool, error)); ok {
		return returnFunc(ctx, familyId, userId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) bool); ok {
		r0 = returnFunc(ctx, familyId, userId)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, familyId, userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_IsUserMemberOfFamily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsUserMemberOfFamily'
type MockRepository_IsUserMemberOfFamily_Call struct {
	*mock.Call
}

// IsUserMemberOfFamily is a helper method to define mock.On call
//   - ctx context.Context
//   - familyId uuid.UUID
//   - userId string
func (_e *MockRepository_Expecter) IsUserMemberOfFamily(ctx interface{}, familyId interface{}, userId interface{}) *MockRepository_IsUserMemberOfFamily_Call {
	return &MockRepository_IsUserMemberOfFamily_Call{Call: _e.mock.On("IsUserMemberOfFamily", ctx, familyId, userId)}
}

func (_c *MockRepository_IsUserMemberOfFamily_Call) Run(run func(ctx context.Context, familyId uuid.UUID, userId string)) *MockRepository_IsUserMemberOfFamily_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_IsUserMemberOfFamily_Call) Return(b bool, err error) *MockRepository_IsUserMemberOfFamily_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRepository_IsUserMemberOfFamily_Call) RunAndReturn(run func(ctx context.Context, familyId uuid.UUID, userId string) (bool, error)) *MockRepository_IsUserMemberOfFamily_Call {
	_c.Call.Return(run)
	return _c
}

// MemberExists provides a mock function for the type MockRepository
func (_mock *MockRepository) MemberExists(ctx context.Context, familyId uuid.UUID, members ...uuid.UUID) (bool, error) {
	var tmpRet mock.Arguments
	if len(members) > 0 {
		tmpRet = _mock.Called(ctx, familyId, members)
	} else {
		tmpRet = _mock.Called(ctx, familyId)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for MemberExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, familyId, members...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, familyId, members...)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...uuid.UUID) error); ok {
		r1 = returnFunc(ctx, familyId, members...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_MemberExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MemberExists'
type MockRepository_MemberExists_Call struct {
	*mock.Call
}

// MemberExists is a helper method to define mock.On call
//   - ctx context.Context
//   - familyId uuid.UUID
//   - members ...uuid.UUID
func (_e *MockRepository_Expecter) MemberExists(ctx interface{}, familyId interface{}, members ...interface{}) *MockRepository_MemberExists_Call {
	return &MockRepository_MemberExists_Call{Call: _e.mock.On("MemberExists",
		append([]interface{}{ctx, familyId}, members...)...)}
}

func (_c *MockRepository_MemberExists_Call) Run(run func(ctx context.Context, familyId uuid.UUID, members ...uuid.UUID)) *MockRepository_MemberExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []uuid.UUID
		var variadicArgs []uuid.UUID
		if len(args) > 2 {
			variadicArgs = args[2].([]uuid.UUID)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockRepository_MemberExists_Call) Return(b bool, err error) *MockRepository_MemberExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRepository_MemberExists_Call) RunAndReturn(run func(ctx context.Context, familyId uuid.UUID, members ...uuid.UUID) (bool, error)) *MockRepository_MemberExists_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockRepository
func (_mock *MockRepository) Save(ctx context.Context, entities ...Family) error {
	var tmpRet mock.Arguments
	if len(entities) > 0 {
		tmpRet = _mock.Called(ctx, entities)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...Family) error); ok {
		r0 = returnFunc(ctx, entities...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - entities ...Family
func (_e *MockRepository_Expecter) Save(ctx interface{}, entities ...interface{}) *MockRepository_Save_Call {
	return &MockRepository_Save_Call{Call: _e.mock.On("Save",
		append([]interface{}{ctx}, entities...)...)}
}

func (_c *MockRepository_Save_Call) Run(run func(ctx context.Context, entities ...Family)) *MockRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []Family
		var variadicArgs []Family
		if len(args) > 1 {
			variadicArgs = args[1].([]Family)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockRepository_Save_Call) Return(err error) *MockRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Save_Call) RunAndReturn(run func(ctx context.Context, entities ...Family) error) *MockRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
