/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHttpErrorFromDiscriminatorValue, createPriceModelFromDiscriminatorValue, serializePriceModel, serializeUpdatePriceModel, type HttpError, type PriceModel, type UpdatePriceModel } from '../../../../models/index.js';
// @ts-ignore
import { PricesRequestBuilderNavigationMetadata, PricesRequestBuilderRequestsMetadata, type PricesRequestBuilder } from './prices/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /providers/{providerId}/plans/{planId}
 */
export interface WithPlanItemRequestBuilder extends BaseRequestBuilder<WithPlanItemRequestBuilder> {
    /**
     * The prices property
     */
    get prices(): PricesRequestBuilder;
    /**
     * Update a new price for a provider plan
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PriceModel>}
     * @throws {HttpError} error when the service returns a 400 status code
     */
     put(body: UpdatePriceModel, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PriceModel | undefined>;
    /**
     * Update a new price for a provider plan
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: UpdatePriceModel, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithPlanItemRequestBuilderUriTemplate = "{+baseurl}/providers/{providerId}/plans/{planId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithPlanItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithPlanItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    prices: {
        requestsMetadata: PricesRequestBuilderRequestsMetadata,
        navigationMetadata: PricesRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WithPlanItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: WithPlanItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createHttpErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPriceModelFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeUpdatePriceModel,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
