// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package subscription

import (
	"context"
	"iter"

	"github.com/google/uuid"
	"github.com/mistribe/subtracker/internal/domain/subscription"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockRepository
func (_mock *MockRepository) Delete(ctx context.Context, entityId uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, entityId)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, entityId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, entityId)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, entityId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - entityId uuid.UUID
func (_e *MockRepository_Expecter) Delete(ctx interface{}, entityId interface{}) *MockRepository_Delete_Call {
	return &MockRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, entityId)}
}

func (_c *MockRepository_Delete_Call) Run(run func(ctx context.Context, entityId uuid.UUID)) *MockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Delete_Call) Return(b bool, err error) *MockRepository_Delete_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, entityId uuid.UUID) (bool, error)) *MockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockRepository
func (_mock *MockRepository) Exists(ctx context.Context, ids ...uuid.UUID) (bool, error) {
	var tmpRet mock.Arguments
	if len(ids) > 0 {
		tmpRet = _mock.Called(ctx, ids)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, ids...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, ids...)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...uuid.UUID) error); ok {
		r1 = returnFunc(ctx, ids...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockRepository_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - ids ...uuid.UUID
func (_e *MockRepository_Expecter) Exists(ctx interface{}, ids ...interface{}) *MockRepository_Exists_Call {
	return &MockRepository_Exists_Call{Call: _e.mock.On("Exists",
		append([]interface{}{ctx}, ids...)...)}
}

func (_c *MockRepository_Exists_Call) Run(run func(ctx context.Context, ids ...uuid.UUID)) *MockRepository_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		var variadicArgs []uuid.UUID
		if len(args) > 1 {
			variadicArgs = args[1].([]uuid.UUID)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockRepository_Exists_Call) Return(b bool, err error) *MockRepository_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRepository_Exists_Call) RunAndReturn(run func(ctx context.Context, ids ...uuid.UUID) (bool, error)) *MockRepository_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockRepository
func (_mock *MockRepository) GetAll(ctx context.Context, parameters subscription.QueryParameters) ([]subscription.Subscription, int64, error) {
	ret := _mock.Called(ctx, parameters)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []subscription.Subscription
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, subscription.QueryParameters) ([]subscription.Subscription, int64, error)); ok {
		return returnFunc(ctx, parameters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, subscription.QueryParameters) []subscription.Subscription); ok {
		r0 = returnFunc(ctx, parameters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]subscription.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, subscription.QueryParameters) int64); ok {
		r1 = returnFunc(ctx, parameters)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, subscription.QueryParameters) error); ok {
		r2 = returnFunc(ctx, parameters)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - parameters subscription.QueryParameters
func (_e *MockRepository_Expecter) GetAll(ctx interface{}, parameters interface{}) *MockRepository_GetAll_Call {
	return &MockRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx, parameters)}
}

func (_c *MockRepository_GetAll_Call) Run(run func(ctx context.Context, parameters subscription.QueryParameters)) *MockRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 subscription.QueryParameters
		if args[1] != nil {
			arg1 = args[1].(subscription.QueryParameters)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetAll_Call) Return(subscriptions []subscription.Subscription, n int64, err error) *MockRepository_GetAll_Call {
	_c.Call.Return(subscriptions, n, err)
	return _c
}

func (_c *MockRepository_GetAll_Call) RunAndReturn(run func(ctx context.Context, parameters subscription.QueryParameters) ([]subscription.Subscription, int64, error)) *MockRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllForUser provides a mock function for the type MockRepository
func (_mock *MockRepository) GetAllForUser(ctx context.Context, userId string, parameters subscription.QueryParameters) ([]subscription.Subscription, int64, error) {
	ret := _mock.Called(ctx, userId, parameters)

	if len(ret) == 0 {
		panic("no return value specified for GetAllForUser")
	}

	var r0 []subscription.Subscription
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, subscription.QueryParameters) ([]subscription.Subscription, int64, error)); ok {
		return returnFunc(ctx, userId, parameters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, subscription.QueryParameters) []subscription.Subscription); ok {
		r0 = returnFunc(ctx, userId, parameters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]subscription.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, subscription.QueryParameters) int64); ok {
		r1 = returnFunc(ctx, userId, parameters)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, subscription.QueryParameters) error); ok {
		r2 = returnFunc(ctx, userId, parameters)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepository_GetAllForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllForUser'
type MockRepository_GetAllForUser_Call struct {
	*mock.Call
}

// GetAllForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userId string
//   - parameters subscription.QueryParameters
func (_e *MockRepository_Expecter) GetAllForUser(ctx interface{}, userId interface{}, parameters interface{}) *MockRepository_GetAllForUser_Call {
	return &MockRepository_GetAllForUser_Call{Call: _e.mock.On("GetAllForUser", ctx, userId, parameters)}
}

func (_c *MockRepository_GetAllForUser_Call) Run(run func(ctx context.Context, userId string, parameters subscription.QueryParameters)) *MockRepository_GetAllForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 subscription.QueryParameters
		if args[2] != nil {
			arg2 = args[2].(subscription.QueryParameters)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_GetAllForUser_Call) Return(subscriptions []subscription.Subscription, n int64, err error) *MockRepository_GetAllForUser_Call {
	_c.Call.Return(subscriptions, n, err)
	return _c
}

func (_c *MockRepository_GetAllForUser_Call) RunAndReturn(run func(ctx context.Context, userId string, parameters subscription.QueryParameters) ([]subscription.Subscription, int64, error)) *MockRepository_GetAllForUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllIt provides a mock function for the type MockRepository
func (_mock *MockRepository) GetAllIt(ctx context.Context, userId string, searchText string) iter.Seq[subscription.Subscription] {
	ret := _mock.Called(ctx, userId, searchText)

	if len(ret) == 0 {
		panic("no return value specified for GetAllIt")
	}

	var r0 iter.Seq[subscription.Subscription]
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) iter.Seq[subscription.Subscription]); ok {
		r0 = returnFunc(ctx, userId, searchText)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iter.Seq[subscription.Subscription])
		}
	}
	return r0
}

// MockRepository_GetAllIt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllIt'
type MockRepository_GetAllIt_Call struct {
	*mock.Call
}

// GetAllIt is a helper method to define mock.On call
//   - ctx context.Context
//   - userId string
//   - searchText string
func (_e *MockRepository_Expecter) GetAllIt(ctx interface{}, userId interface{}, searchText interface{}) *MockRepository_GetAllIt_Call {
	return &MockRepository_GetAllIt_Call{Call: _e.mock.On("GetAllIt", ctx, userId, searchText)}
}

func (_c *MockRepository_GetAllIt_Call) Run(run func(ctx context.Context, userId string, searchText string)) *MockRepository_GetAllIt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_GetAllIt_Call) Return(seq iter.Seq[subscription.Subscription]) *MockRepository_GetAllIt_Call {
	_c.Call.Return(seq)
	return _c
}

func (_c *MockRepository_GetAllIt_Call) RunAndReturn(run func(ctx context.Context, userId string, searchText string) iter.Seq[subscription.Subscription]) *MockRepository_GetAllIt_Call {
	_c.Call.Return(run)
	return _c
}

// GetById provides a mock function for the type MockRepository
func (_mock *MockRepository) GetById(ctx context.Context, entityId uuid.UUID) (subscription.Subscription, error) {
	ret := _mock.Called(ctx, entityId)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 subscription.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (subscription.Subscription, error)); ok {
		return returnFunc(ctx, entityId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) subscription.Subscription); ok {
		r0 = returnFunc(ctx, entityId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(subscription.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, entityId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type MockRepository_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - ctx context.Context
//   - entityId uuid.UUID
func (_e *MockRepository_Expecter) GetById(ctx interface{}, entityId interface{}) *MockRepository_GetById_Call {
	return &MockRepository_GetById_Call{Call: _e.mock.On("GetById", ctx, entityId)}
}

func (_c *MockRepository_GetById_Call) Run(run func(ctx context.Context, entityId uuid.UUID)) *MockRepository_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetById_Call) Return(subscription1 subscription.Subscription, err error) *MockRepository_GetById_Call {
	_c.Call.Return(subscription1, err)
	return _c
}

func (_c *MockRepository_GetById_Call) RunAndReturn(run func(ctx context.Context, entityId uuid.UUID) (subscription.Subscription, error)) *MockRepository_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIdForUser provides a mock function for the type MockRepository
func (_mock *MockRepository) GetByIdForUser(ctx context.Context, userId string, id uuid.UUID) (subscription.Subscription, error) {
	ret := _mock.Called(ctx, userId, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByIdForUser")
	}

	var r0 subscription.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) (subscription.Subscription, error)); ok {
		return returnFunc(ctx, userId, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) subscription.Subscription); ok {
		r0 = returnFunc(ctx, userId, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(subscription.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userId, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetByIdForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIdForUser'
type MockRepository_GetByIdForUser_Call struct {
	*mock.Call
}

// GetByIdForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userId string
//   - id uuid.UUID
func (_e *MockRepository_Expecter) GetByIdForUser(ctx interface{}, userId interface{}, id interface{}) *MockRepository_GetByIdForUser_Call {
	return &MockRepository_GetByIdForUser_Call{Call: _e.mock.On("GetByIdForUser", ctx, userId, id)}
}

func (_c *MockRepository_GetByIdForUser_Call) Run(run func(ctx context.Context, userId string, id uuid.UUID)) *MockRepository_GetByIdForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_GetByIdForUser_Call) Return(subscription1 subscription.Subscription, err error) *MockRepository_GetByIdForUser_Call {
	_c.Call.Return(subscription1, err)
	return _c
}

func (_c *MockRepository_GetByIdForUser_Call) RunAndReturn(run func(ctx context.Context, userId string, id uuid.UUID) (subscription.Subscription, error)) *MockRepository_GetByIdForUser_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockRepository
func (_mock *MockRepository) Save(ctx context.Context, entities ...subscription.Subscription) error {
	var tmpRet mock.Arguments
	if len(entities) > 0 {
		tmpRet = _mock.Called(ctx, entities)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...subscription.Subscription) error); ok {
		r0 = returnFunc(ctx, entities...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - entities ...subscription.Subscription
func (_e *MockRepository_Expecter) Save(ctx interface{}, entities ...interface{}) *MockRepository_Save_Call {
	return &MockRepository_Save_Call{Call: _e.mock.On("Save",
		append([]interface{}{ctx}, entities...)...)}
}

func (_c *MockRepository_Save_Call) Run(run func(ctx context.Context, entities ...subscription.Subscription)) *MockRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []subscription.Subscription
		var variadicArgs []subscription.Subscription
		if len(args) > 1 {
			variadicArgs = args[1].([]subscription.Subscription)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockRepository_Save_Call) Return(err error) *MockRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Save_Call) RunAndReturn(run func(ctx context.Context, entities ...subscription.Subscription) error) *MockRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
