// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package user

import (
	"context"

	"github.com/mistribe/subtracker/internal/domain/currency"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// GetPreferredCurrency provides a mock function for the type MockService
func (_mock *MockService) GetPreferredCurrency(ctx context.Context, userId string) currency.Unit {
	ret := _mock.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetPreferredCurrency")
	}

	var r0 currency.Unit
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) currency.Unit); ok {
		r0 = returnFunc(ctx, userId)
	} else {
		r0 = ret.Get(0).(currency.Unit)
	}
	return r0
}

// MockService_GetPreferredCurrency_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPreferredCurrency'
type MockService_GetPreferredCurrency_Call struct {
	*mock.Call
}

// GetPreferredCurrency is a helper method to define mock.On call
//   - ctx context.Context
//   - userId string
func (_e *MockService_Expecter) GetPreferredCurrency(ctx interface{}, userId interface{}) *MockService_GetPreferredCurrency_Call {
	return &MockService_GetPreferredCurrency_Call{Call: _e.mock.On("GetPreferredCurrency", ctx, userId)}
}

func (_c *MockService_GetPreferredCurrency_Call) Run(run func(ctx context.Context, userId string)) *MockService_GetPreferredCurrency_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetPreferredCurrency_Call) Return(v currency.Unit) *MockService_GetPreferredCurrency_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockService_GetPreferredCurrency_Call) RunAndReturn(run func(ctx context.Context, userId string) currency.Unit) *MockService_GetPreferredCurrency_Call {
	_c.Call.Return(run)
	return _c
}
