/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createCurrencyRatesModelFromDiscriminatorValue, createHttpErrorResponseFromDiscriminatorValue, type CurrencyRatesModel, type HttpErrorResponse } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /currencies/rates/refresh
 */
export interface RefreshRequestBuilder extends BaseRequestBuilder<RefreshRequestBuilder> {
    /**
     * refresh exchange rates for all currencies
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CurrencyRatesModel>}
     * @throws {HttpErrorResponse} error when the service returns a 400 status code
     * @throws {HttpErrorResponse} error when the service returns a 500 status code
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CurrencyRatesModel | undefined>;
    /**
     * refresh exchange rates for all currencies
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const RefreshRequestBuilderUriTemplate = "{+baseurl}/currencies/rates/refresh";
/**
 * Metadata for all the requests in the request builder.
 */
export const RefreshRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: RefreshRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createHttpErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createHttpErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCurrencyRatesModelFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
