/* tslint:disable */
/* eslint-disable */
/**
 * SubTracker API
 * This api provide HTTPRest endpoints for the application SubTracker.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@mistribe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DtoEditableOwnerModel } from './DtoEditableOwnerModel';
import {
    DtoEditableOwnerModelFromJSON,
    DtoEditableOwnerModelFromJSONTyped,
    DtoEditableOwnerModelToJSON,
    DtoEditableOwnerModelToJSONTyped,
} from './DtoEditableOwnerModel';

/**
 * 
 * @export
 * @interface DtoCreateProviderRequest
 */
export interface DtoCreateProviderRequest {
    /**
     * 
     * @type {Date}
     * @memberof DtoCreateProviderRequest
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof DtoCreateProviderRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoCreateProviderRequest
     */
    iconUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoCreateProviderRequest
     */
    id?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof DtoCreateProviderRequest
     */
    labels: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof DtoCreateProviderRequest
     */
    name: string;
    /**
     * 
     * @type {DtoEditableOwnerModel}
     * @memberof DtoCreateProviderRequest
     */
    owner: DtoEditableOwnerModel;
    /**
     * 
     * @type {string}
     * @memberof DtoCreateProviderRequest
     */
    pricingPageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoCreateProviderRequest
     */
    url?: string;
}

/**
 * Check if a given object implements the DtoCreateProviderRequest interface.
 */
export function instanceOfDtoCreateProviderRequest(value: object): value is DtoCreateProviderRequest {
    if (!('labels' in value) || value['labels'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('owner' in value) || value['owner'] === undefined) return false;
    return true;
}

export function DtoCreateProviderRequestFromJSON(json: any): DtoCreateProviderRequest {
    return DtoCreateProviderRequestFromJSONTyped(json, false);
}

export function DtoCreateProviderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoCreateProviderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'description': json['description'] == null ? undefined : json['description'],
        'iconUrl': json['icon_url'] == null ? undefined : json['icon_url'],
        'id': json['id'] == null ? undefined : json['id'],
        'labels': json['labels'],
        'name': json['name'],
        'owner': DtoEditableOwnerModelFromJSON(json['owner']),
        'pricingPageUrl': json['pricing_page_url'] == null ? undefined : json['pricing_page_url'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function DtoCreateProviderRequestToJSON(json: any): DtoCreateProviderRequest {
    return DtoCreateProviderRequestToJSONTyped(json, false);
}

export function DtoCreateProviderRequestToJSONTyped(value?: DtoCreateProviderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'description': value['description'],
        'icon_url': value['iconUrl'],
        'id': value['id'],
        'labels': value['labels'],
        'name': value['name'],
        'owner': DtoEditableOwnerModelToJSON(value['owner']),
        'pricing_page_url': value['pricingPageUrl'],
        'url': value['url'],
    };
}

