/* tslint:disable */
/* eslint-disable */
/**
 * SubTracker API
 * This api provide HTTPRest endpoints for the application SubTracker.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@mistribe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DtoFamilyAcceptInvitationRequest
 */
export interface DtoFamilyAcceptInvitationRequest {
    /**
     * ID of the family member accepting the invitation
     * @type {string}
     * @memberof DtoFamilyAcceptInvitationRequest
     */
    familyMemberId: string;
    /**
     * Code received in the invitation
     * @type {string}
     * @memberof DtoFamilyAcceptInvitationRequest
     */
    invitationCode: string;
}

/**
 * Check if a given object implements the DtoFamilyAcceptInvitationRequest interface.
 */
export function instanceOfDtoFamilyAcceptInvitationRequest(value: object): value is DtoFamilyAcceptInvitationRequest {
    if (!('familyMemberId' in value) || value['familyMemberId'] === undefined) return false;
    if (!('invitationCode' in value) || value['invitationCode'] === undefined) return false;
    return true;
}

export function DtoFamilyAcceptInvitationRequestFromJSON(json: any): DtoFamilyAcceptInvitationRequest {
    return DtoFamilyAcceptInvitationRequestFromJSONTyped(json, false);
}

export function DtoFamilyAcceptInvitationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoFamilyAcceptInvitationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'familyMemberId': json['family_member_id'],
        'invitationCode': json['invitation_code'],
    };
}

export function DtoFamilyAcceptInvitationRequestToJSON(json: any): DtoFamilyAcceptInvitationRequest {
    return DtoFamilyAcceptInvitationRequestToJSONTyped(json, false);
}

export function DtoFamilyAcceptInvitationRequestToJSONTyped(value?: DtoFamilyAcceptInvitationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'family_member_id': value['familyMemberId'],
        'invitation_code': value['invitationCode'],
    };
}

