/* tslint:disable */
/* eslint-disable */
/**
 * SubTracker API
 * This api provide HTTPRest endpoints for the application SubTracker.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@mistribe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DtoFamilyInviteResponse
 */
export interface DtoFamilyInviteResponse {
    /**
     * 
     * @type {string}
     * @memberof DtoFamilyInviteResponse
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof DtoFamilyInviteResponse
     */
    familyId: string;
    /**
     * 
     * @type {string}
     * @memberof DtoFamilyInviteResponse
     */
    familyMemberId: string;
}

/**
 * Check if a given object implements the DtoFamilyInviteResponse interface.
 */
export function instanceOfDtoFamilyInviteResponse(value: object): value is DtoFamilyInviteResponse {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('familyId' in value) || value['familyId'] === undefined) return false;
    if (!('familyMemberId' in value) || value['familyMemberId'] === undefined) return false;
    return true;
}

export function DtoFamilyInviteResponseFromJSON(json: any): DtoFamilyInviteResponse {
    return DtoFamilyInviteResponseFromJSONTyped(json, false);
}

export function DtoFamilyInviteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoFamilyInviteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'familyId': json['family_id'],
        'familyMemberId': json['family_member_id'],
    };
}

export function DtoFamilyInviteResponseToJSON(json: any): DtoFamilyInviteResponse {
    return DtoFamilyInviteResponseToJSONTyped(json, false);
}

export function DtoFamilyInviteResponseToJSONTyped(value?: DtoFamilyInviteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'family_id': value['familyId'],
        'family_member_id': value['familyMemberId'],
    };
}

