/* tslint:disable */
/* eslint-disable */
/**
 * SubTracker API
 * This api provide HTTPRest endpoints for the application SubTracker.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@mistribe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DtoLimit } from './DtoLimit';
import {
    DtoLimitFromJSON,
    DtoLimitFromJSONTyped,
    DtoLimitToJSON,
    DtoLimitToJSONTyped,
} from './DtoLimit';
import type { DtoLabelModel } from './DtoLabelModel';
import {
    DtoLabelModelFromJSON,
    DtoLabelModelFromJSONTyped,
    DtoLabelModelToJSON,
    DtoLabelModelToJSONTyped,
} from './DtoLabelModel';

/**
 * 
 * @export
 * @interface DtoPaginatedResponseModelDtoLabelModel
 */
export interface DtoPaginatedResponseModelDtoLabelModel {
    /**
     * Data contains the list of items for the current page
     * @type {Array<DtoLabelModel>}
     * @memberof DtoPaginatedResponseModelDtoLabelModel
     */
    data: Array<DtoLabelModel>;
    /**
     * Length represents the number of items in the current page
     * @type {number}
     * @memberof DtoPaginatedResponseModelDtoLabelModel
     */
    length: number;
    /**
     * 
     * @type {Array<DtoLimit>}
     * @memberof DtoPaginatedResponseModelDtoLabelModel
     */
    limit?: Array<DtoLimit>;
    /**
     * Total represents the total number of items available
     * @type {number}
     * @memberof DtoPaginatedResponseModelDtoLabelModel
     */
    total: number;
}

/**
 * Check if a given object implements the DtoPaginatedResponseModelDtoLabelModel interface.
 */
export function instanceOfDtoPaginatedResponseModelDtoLabelModel(value: object): value is DtoPaginatedResponseModelDtoLabelModel {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('length' in value) || value['length'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function DtoPaginatedResponseModelDtoLabelModelFromJSON(json: any): DtoPaginatedResponseModelDtoLabelModel {
    return DtoPaginatedResponseModelDtoLabelModelFromJSONTyped(json, false);
}

export function DtoPaginatedResponseModelDtoLabelModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoPaginatedResponseModelDtoLabelModel {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(DtoLabelModelFromJSON)),
        'length': json['length'],
        'limit': json['limit'] == null ? undefined : ((json['limit'] as Array<any>).map(DtoLimitFromJSON)),
        'total': json['total'],
    };
}

export function DtoPaginatedResponseModelDtoLabelModelToJSON(json: any): DtoPaginatedResponseModelDtoLabelModel {
    return DtoPaginatedResponseModelDtoLabelModelToJSONTyped(json, false);
}

export function DtoPaginatedResponseModelDtoLabelModelToJSONTyped(value?: DtoPaginatedResponseModelDtoLabelModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(DtoLabelModelToJSON)),
        'length': value['length'],
        'limit': value['limit'] == null ? undefined : ((value['limit'] as Array<any>).map(DtoLimitToJSON)),
        'total': value['total'],
    };
}

