/* tslint:disable */
/* eslint-disable */
/**
 * SubTracker API
 * This api provide HTTPRest endpoints for the application SubTracker.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@mistribe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DtoAmountModel } from './DtoAmountModel';
import {
    DtoAmountModelFromJSON,
    DtoAmountModelFromJSONTyped,
    DtoAmountModelToJSON,
    DtoAmountModelToJSONTyped,
} from './DtoAmountModel';

/**
 * 
 * @export
 * @interface DtoSubscriptionSummaryTopProviderResponse
 */
export interface DtoSubscriptionSummaryTopProviderResponse {
    /**
     * 
     * @type {string}
     * @memberof DtoSubscriptionSummaryTopProviderResponse
     */
    duration?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoSubscriptionSummaryTopProviderResponse
     */
    providerId: string;
    /**
     * 
     * @type {DtoAmountModel}
     * @memberof DtoSubscriptionSummaryTopProviderResponse
     */
    total?: DtoAmountModel;
}

/**
 * Check if a given object implements the DtoSubscriptionSummaryTopProviderResponse interface.
 */
export function instanceOfDtoSubscriptionSummaryTopProviderResponse(value: object): value is DtoSubscriptionSummaryTopProviderResponse {
    if (!('providerId' in value) || value['providerId'] === undefined) return false;
    return true;
}

export function DtoSubscriptionSummaryTopProviderResponseFromJSON(json: any): DtoSubscriptionSummaryTopProviderResponse {
    return DtoSubscriptionSummaryTopProviderResponseFromJSONTyped(json, false);
}

export function DtoSubscriptionSummaryTopProviderResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoSubscriptionSummaryTopProviderResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'duration': json['duration'] == null ? undefined : json['duration'],
        'providerId': json['provider_id'],
        'total': json['total'] == null ? undefined : DtoAmountModelFromJSON(json['total']),
    };
}

export function DtoSubscriptionSummaryTopProviderResponseToJSON(json: any): DtoSubscriptionSummaryTopProviderResponse {
    return DtoSubscriptionSummaryTopProviderResponseToJSONTyped(json, false);
}

export function DtoSubscriptionSummaryTopProviderResponseToJSONTyped(value?: DtoSubscriptionSummaryTopProviderResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'duration': value['duration'],
        'provider_id': value['providerId'],
        'total': DtoAmountModelToJSON(value['total']),
    };
}

