/* tslint:disable */
/* eslint-disable */
/**
 * SubTracker API
 * This api provide HTTPRest endpoints for the application SubTracker.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@mistribe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DtoSubscriptionFreeTrialModel } from './DtoSubscriptionFreeTrialModel';
import {
    DtoSubscriptionFreeTrialModelFromJSON,
    DtoSubscriptionFreeTrialModelFromJSONTyped,
    DtoSubscriptionFreeTrialModelToJSON,
    DtoSubscriptionFreeTrialModelToJSONTyped,
} from './DtoSubscriptionFreeTrialModel';
import type { DtoAmountModel } from './DtoAmountModel';
import {
    DtoAmountModelFromJSON,
    DtoAmountModelFromJSONTyped,
    DtoAmountModelToJSON,
    DtoAmountModelToJSONTyped,
} from './DtoAmountModel';
import type { DtoEditableSubscriptionPayerModel } from './DtoEditableSubscriptionPayerModel';
import {
    DtoEditableSubscriptionPayerModelFromJSON,
    DtoEditableSubscriptionPayerModelFromJSONTyped,
    DtoEditableSubscriptionPayerModelToJSON,
    DtoEditableSubscriptionPayerModelToJSONTyped,
} from './DtoEditableSubscriptionPayerModel';

/**
 * 
 * @export
 * @interface DtoUpdateSubscriptionRequest
 */
export interface DtoUpdateSubscriptionRequest {
    /**
     * 
     * @type {number}
     * @memberof DtoUpdateSubscriptionRequest
     */
    customRecurrency?: number;
    /**
     * 
     * @type {Date}
     * @memberof DtoUpdateSubscriptionRequest
     */
    endDate?: Date;
    /**
     * 
     * @type {DtoSubscriptionFreeTrialModel}
     * @memberof DtoUpdateSubscriptionRequest
     */
    freeTrial?: DtoSubscriptionFreeTrialModel;
    /**
     * 
     * @type {string}
     * @memberof DtoUpdateSubscriptionRequest
     */
    friendlyName?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof DtoUpdateSubscriptionRequest
     */
    labels?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof DtoUpdateSubscriptionRequest
     */
    owner: DtoUpdateSubscriptionRequestOwnerEnum;
    /**
     * 
     * @type {DtoEditableSubscriptionPayerModel}
     * @memberof DtoUpdateSubscriptionRequest
     */
    payer?: DtoEditableSubscriptionPayerModel;
    /**
     * 
     * @type {DtoAmountModel}
     * @memberof DtoUpdateSubscriptionRequest
     */
    price?: DtoAmountModel;
    /**
     * 
     * @type {string}
     * @memberof DtoUpdateSubscriptionRequest
     */
    providerId: string;
    /**
     * 
     * @type {string}
     * @memberof DtoUpdateSubscriptionRequest
     */
    recurrency: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof DtoUpdateSubscriptionRequest
     */
    serviceUsers?: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof DtoUpdateSubscriptionRequest
     */
    startDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof DtoUpdateSubscriptionRequest
     */
    updatedAt?: Date;
}


/**
 * @export
 */
export const DtoUpdateSubscriptionRequestOwnerEnum = {
    Personal: 'personal',
    Family: 'family',
    System: 'system'
} as const;
export type DtoUpdateSubscriptionRequestOwnerEnum = typeof DtoUpdateSubscriptionRequestOwnerEnum[keyof typeof DtoUpdateSubscriptionRequestOwnerEnum];


/**
 * Check if a given object implements the DtoUpdateSubscriptionRequest interface.
 */
export function instanceOfDtoUpdateSubscriptionRequest(value: object): value is DtoUpdateSubscriptionRequest {
    if (!('owner' in value) || value['owner'] === undefined) return false;
    if (!('providerId' in value) || value['providerId'] === undefined) return false;
    if (!('recurrency' in value) || value['recurrency'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    return true;
}

export function DtoUpdateSubscriptionRequestFromJSON(json: any): DtoUpdateSubscriptionRequest {
    return DtoUpdateSubscriptionRequestFromJSONTyped(json, false);
}

export function DtoUpdateSubscriptionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoUpdateSubscriptionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'customRecurrency': json['custom_recurrency'] == null ? undefined : json['custom_recurrency'],
        'endDate': json['end_date'] == null ? undefined : (new Date(json['end_date'])),
        'freeTrial': json['free_trial'] == null ? undefined : DtoSubscriptionFreeTrialModelFromJSON(json['free_trial']),
        'friendlyName': json['friendly_name'] == null ? undefined : json['friendly_name'],
        'labels': json['labels'] == null ? undefined : json['labels'],
        'owner': json['owner'],
        'payer': json['payer'] == null ? undefined : DtoEditableSubscriptionPayerModelFromJSON(json['payer']),
        'price': json['price'] == null ? undefined : DtoAmountModelFromJSON(json['price']),
        'providerId': json['provider_id'],
        'recurrency': json['recurrency'],
        'serviceUsers': json['service_users'] == null ? undefined : json['service_users'],
        'startDate': (new Date(json['start_date'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function DtoUpdateSubscriptionRequestToJSON(json: any): DtoUpdateSubscriptionRequest {
    return DtoUpdateSubscriptionRequestToJSONTyped(json, false);
}

export function DtoUpdateSubscriptionRequestToJSONTyped(value?: DtoUpdateSubscriptionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'custom_recurrency': value['customRecurrency'],
        'end_date': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString(),
        'free_trial': DtoSubscriptionFreeTrialModelToJSON(value['freeTrial']),
        'friendly_name': value['friendlyName'],
        'labels': value['labels'],
        'owner': value['owner'],
        'payer': DtoEditableSubscriptionPayerModelToJSON(value['payer']),
        'price': DtoAmountModelToJSON(value['price']),
        'provider_id': value['providerId'],
        'recurrency': value['recurrency'],
        'service_users': value['serviceUsers'],
        'start_date': value['startDate'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

