/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpdatePreferredCurrencyModel}
 */
// @ts-ignore
export function createUpdatePreferredCurrencyModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpdatePreferredCurrencyModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UserPreferredCurrencyModel}
 */
// @ts-ignore
export function createUserPreferredCurrencyModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUserPreferredCurrencyModel;
}
/**
 * The deserialization information for the current model
 * @param UpdatePreferredCurrencyModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpdatePreferredCurrencyModel(updatePreferredCurrencyModel: Partial<UpdatePreferredCurrencyModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "currency": n => { updatePreferredCurrencyModel.currency = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param UserPreferredCurrencyModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUserPreferredCurrencyModel(userPreferredCurrencyModel: Partial<UserPreferredCurrencyModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "currency": n => { userPreferredCurrencyModel.currency = n.getStringValue(); },
    }
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UpdatePreferredCurrencyModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpdatePreferredCurrencyModel(writer: SerializationWriter, updatePreferredCurrencyModel: Partial<UpdatePreferredCurrencyModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!updatePreferredCurrencyModel || isSerializingDerivedType) { return; }
    writer.writeStringValue("currency", updatePreferredCurrencyModel.currency);
    writer.writeAdditionalData(updatePreferredCurrencyModel.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UserPreferredCurrencyModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUserPreferredCurrencyModel(writer: SerializationWriter, userPreferredCurrencyModel: Partial<UserPreferredCurrencyModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!userPreferredCurrencyModel || isSerializingDerivedType) { return; }
    writer.writeStringValue("currency", userPreferredCurrencyModel.currency);
    writer.writeAdditionalData(userPreferredCurrencyModel.additionalData);
}
export interface UpdatePreferredCurrencyModel extends AdditionalDataHolder, Parsable {
    /**
     * The currency property
     */
    currency?: string | null;
}
export interface UserPreferredCurrencyModel extends AdditionalDataHolder, Parsable {
    /**
     * The currency property
     */
    currency?: string | null;
}
/* tslint:enable */
/* eslint-enable */
