name: Web Build and Test

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'
      - '.github/workflows/web-build.yml'
  pull_request:
    paths:
      - 'web/**'
      - '.github/workflows/web-build.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build and Test (web)
    runs-on: ubuntu-latest
    env:
      CI: true
    defaults:
      run:
        working-directory: web
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'web/package-lock.json'

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build
        run: npm run build
# Enable when we have tests
#      - name: Test
#        run: npm test
